.github/workflows/deploy.yml, src/main/java/com/service/indianfrog/domain/chat/controller/ChatController.java, src/main/java/com/service/indianfrog/domain/chat/controller/WebSocketEventListener.java, src/main/java/com/service/indianfrog/domain/chat/entity/ChatMessage.java, src/main/java/com/service/indianfrog/domain/gameroom/controller/GameRoomController.java, src/main/java/com/service/indianfrog/domain/gameroom/dto/GameRoomDto.java, src/main/java/com/service/indianfrog/domain/gameroom/entity/GameRoom.java, src/main/java/com/service/indianfrog/domain/gameroom/entity/ValidateRoom.java, src/main/java/com/service/indianfrog/domain/gameroom/repository/GameRoomRepository.java, src/main/java/com/service/indianfrog/domain/gameroom/repository/ValidateRoomRepository.java, src/main/java/com/service/indianfrog/domain/gameroom/service/GameRoomService.java, src/main/java/com/service/indianfrog/global/config/WebSocketConfig.java, src/main/java/com/service/indianfrog/global/properties/RedisProperties.java, src/main/resources/application.yml
웹소켓 채팅
게임방 생성
게임방 입장&퇴장 시 참가자 기록
모든 참가자가 퇴장 시 게임방 삭제
=> feat: 채팅,게임방 기능구현 #24

.github/workflows/deploy.yml
=> Fix: container config error 수정 #17

src/main/java/com/service/indianfrog/global/security/JwtAuthenticationFilter.java
=> fix: update cookie secure->RUN IN HTTPS

src/main/java/com/service/indianfrog/global/security/JwtAuthenticationFilter.java, src/main/java/com/service/indianfrog/global/security/token/RefreshController.java
=> fix: update cookie Attribute about samesite

src/main/java/com/service/indianfrog/domain/game/controller/GameController.java, src/main/java/com/service/indianfrog/domain/game/dto/GameBetting.java
GameController Input 변경
기존 chatMessage -> gameBetting 으로 입력 변수 변경
=> GameController Input 변경

src/main/java/com/service/indianfrog/domain/gameroom/dto/ParticipantInfo.java, src/main/java/com/service/indianfrog/domain/gameroom/service/GameRoomService.java
=> fix: ParticipantInfo에 host 정보 추가

src/main/java/com/service/indianfrog/domain/game/controller/GameController.java, src/main/java/com/service/indianfrog/domain/game/dto/PlayerInfo.java, src/main/java/com/service/indianfrog/domain/game/utils/GameValidator.java, src/main/java/com/service/indianfrog/domain/gameroom/service/GameRoomService.java, src/main/java/com/service/indianfrog/global/config/WebSocketConfig.java
=> fix: queue 수정

src/main/java/com/service/indianfrog/global/security/JwtAuthenticationFilter.java, src/main/java/com/service/indianfrog/global/security/token/RefreshTokenService.java
=> fix: refreshToken 재발급 수정

src/main/java/com/service/indianfrog/domain/gameroom/dto/GameRoomResponseDto.java, src/main/java/com/service/indianfrog/domain/gameroom/service/GameRoomService.java
=> fix: GameRoomResponseDto 수정

src/main/java/com/service/indianfrog/domain/chat/controller/ChatController.java, src/main/java/com/service/indianfrog/domain/chat/entity/ChatMessage.java
=> fix: chat controller #79

src/main/java/com/service/indianfrog/domain/game/entity/Game.java, src/main/java/com/service/indianfrog/domain/gameroom/entity/GameRoom.java, src/main/java/com/service/indianfrog/domain/user/entity/User.java, src/main/java/com/service/indianfrog/global/dto/TokenRequest.java, src/main/java/com/service/indianfrog/global/exception/ErrorCode.java, src/main/java/com/service/indianfrog/global/jwt/JwtUtil.java, src/main/java/com/service/indianfrog/global/security/JwtAuthorizationFilter.java, src/main/java/com/service/indianfrog/global/security/token/RefreshController.java, src/main/java/com/service/indianfrog/global/security/token/RefreshTokenService.java, src/main/resources/static/app.js, src/main/resources/static/index.html, src/test/java/com/service/indianfrog/StartGameServiceTest.java, src/test/java/com/service/indianfrog/domain/game/controller/GameControllerTest.java
update authorization test
TODO :
=> chore: update authorization test

src/main/java/com/service/indianfrog/global/config/WebSocketAuthChannelInterceptor.java, src/main/java/com/service/indianfrog/global/jwt/JwtUtil.java
ChannelInterceptor error message
=> fix: ChannelInterceptor error message # 86

src/main/java/com/service/indianfrog/domain/game/controller/GameController.java, src/main/java/com/service/indianfrog/domain/game/dto/ActionDto.java, src/main/java/com/service/indianfrog/domain/game/dto/EndGameInfo.java, src/main/java/com/service/indianfrog/domain/game/dto/EndRoundInfo.java, src/main/java/com/service/indianfrog/domain/game/dto/GameBetting.java, src/main/java/com/service/indianfrog/domain/game/dto/GameDto.java, src/main/java/com/service/indianfrog/domain/game/dto/GameInfo.java, src/main/java/com/service/indianfrog/domain/game/dto/GameResult.java, src/main/java/com/service/indianfrog/domain/game/entity/Game.java, src/main/java/com/service/indianfrog/domain/game/entity/Turn.java, src/main/java/com/service/indianfrog/domain/game/service/EndGameService.java, src/main/java/com/service/indianfrog/domain/game/service/GamePlayService.java, src/main/java/com/service/indianfrog/domain/game/service/GameTurnService.java, src/main/java/com/service/indianfrog/domain/game/service/StartGameService.java, src/main/java/com/service/indianfrog/domain/game/utils/GameValidator.java, src/main/java/com/service/indianfrog/domain/mypage/dto/MyPageInfo.java, src/test/java/com/service/indianfrog/domain/game/controller/GameControllerTest.java
=> feat: Game로직 수정

src/main/java/com/service/indianfrog/domain/game/controller/GameController.java, src/main/java/com/service/indianfrog/domain/game/dto/EndRoundInfo.java, src/main/java/com/service/indianfrog/domain/game/dto/GameDto.java, src/main/java/com/service/indianfrog/domain/game/service/EndGameService.java, src/main/java/com/service/indianfrog/domain/mypage/service/MyPageService.java, src/main/java/com/service/indianfrog/domain/ranking/controller/RankingController.java, src/main/java/com/service/indianfrog/domain/ranking/dto/Ranking.java, src/main/java/com/service/indianfrog/domain/ranking/service/RankingService.java, src/main/java/com/service/indianfrog/domain/user/repository/UserRepository.java, src/main/java/com/service/indianfrog/global/security/token/RefreshTokenService.java, src/main/resources/yml/application-dev.yml
=> 게임 로직 수정 : mergeX

src/main/java/com/service/indianfrog/domain/game/service/StartGameService.java, src/main/java/com/service/indianfrog/domain/gameroom/service/GameRoomService.java
=> refactor: Pessimistic Lock #132

src/main/java/com/service/indianfrog/domain/game/controller/GameController.java, src/main/java/com/service/indianfrog/domain/game/dto/GameDto.java, src/main/java/com/service/indianfrog/domain/game/dto/GameInfo.java, src/main/java/com/service/indianfrog/domain/game/service/EndGameService.java, src/main/java/com/service/indianfrog/domain/game/service/StartGameService.java, src/main/java/com/service/indianfrog/domain/game/utils/GameValidator.java, src/main/java/com/service/indianfrog/domain/game/utils/RepositoryHolder.java, src/main/java/com/service/indianfrog/domain/gameroom/repository/GameRoomRepository.java, src/main/java/com/service/indianfrog/domain/gameroom/repository/ValidateRoomRepository.java, src/main/java/com/service/indianfrog/domain/gameroom/service/GameRoomService.java
=> fix: 카드값 랜덤 수정 #136

src/main/java/com/service/indianfrog/domain/user/repository/UserRepository.java, src/main/java/com/service/indianfrog/domain/user/service/MailSendService.java, src/main/java/com/service/indianfrog/global/properties/JwtProperties.java, src/main/resources/yml/application-dev.yml
=> jwt path update

src/main/java/com/service/indianfrog/domain/game/entity/Game.java, src/main/java/com/service/indianfrog/domain/game/service/EndGameService.java, src/main/java/com/service/indianfrog/domain/gameroom/entity/GameRoom.java
=> fix: endgame #158

src/main/java/com/service/indianfrog/domain/game/controller/GameController.java, src/main/java/com/service/indianfrog/domain/game/entity/Card.java, src/main/java/com/service/indianfrog/domain/game/service/EndGameService.java, src/main/java/com/service/indianfrog/domain/gameroom/entity/ValidateRoom.java
=> fix: 레디 초기화 #158

src/main/java/com/service/indianfrog/domain/game/entity/Game.java, src/main/java/com/service/indianfrog/domain/game/service/EndGameService.java, src/main/java/com/service/indianfrog/domain/game/service/GamePlayService.java, src/main/java/com/service/indianfrog/domain/game/service/GameSessionService.java, src/main/java/com/service/indianfrog/domain/game/service/StartGameService.java
=> refactor: game lock #161

src/main/java/com/service/indianfrog/domain/game/controller/GameController.java, src/main/java/com/service/indianfrog/domain/game/dto/ActionDto.java, src/main/java/com/service/indianfrog/domain/game/dto/EndRoundInfo.java, src/main/java/com/service/indianfrog/domain/game/dto/GameDto.java, src/main/java/com/service/indianfrog/domain/game/entity/Game.java, src/main/java/com/service/indianfrog/domain/game/entity/Turn.java, src/main/java/com/service/indianfrog/domain/game/service/EndGameService.java, src/main/java/com/service/indianfrog/domain/game/service/GamePlayService.java, src/main/java/com/service/indianfrog/domain/game/service/StartGameService.java, src/main/java/com/service/indianfrog/domain/game/utils/GameValidator.java, src/main/java/com/service/indianfrog/domain/gameroom/entity/GameRoom.java, src/main/java/com/service/indianfrog/domain/user/service/PasswordService.java
=> fix: regame, password update

src/main/java/com/service/indianfrog/domain/game/dto/ActionDto.java, src/main/java/com/service/indianfrog/domain/game/entity/Game.java, src/main/java/com/service/indianfrog/domain/game/service/EndGameService.java, src/main/java/com/service/indianfrog/domain/game/service/GamePlayService.java, src/main/java/com/service/indianfrog/domain/game/service/GameSessionService.java, src/main/java/com/service/indianfrog/domain/game/service/ReadyService.java, src/main/java/com/service/indianfrog/domain/game/service/StartGameService.java
=> fix: 카드 null 수정 #183

src/main/java/com/service/indianfrog/global/config/WebSecurityConfig.java
=> fix: update allowedOriginPattern

src/main/java/com/service/indianfrog/domain/game/controller/GameController.java, src/main/java/com/service/indianfrog/domain/game/dto/ActionDto.java, src/main/java/com/service/indianfrog/domain/game/service/EndGameService.java, src/main/java/com/service/indianfrog/domain/game/service/GamePlayService.java, src/main/java/com/service/indianfrog/domain/game/service/GameSessionService.java, src/main/java/com/service/indianfrog/domain/game/service/GameTurnService.java, src/main/java/com/service/indianfrog/domain/game/service/ReadyService.java, src/main/java/com/service/indianfrog/domain/game/service/SendUserMessageService.java, src/main/java/com/service/indianfrog/domain/game/service/StartGameService.java, src/main/java/com/service/indianfrog/domain/game/utils/ConcurrencyControlService.java
=> Fix controller
